server:
  port: 8042
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zzx?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: dandelion
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    root: INFO